name: callable workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: blabla
        required: true
        type: string
        default: data
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: download the artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: show the downloaded artifact
        run: ls
      - name: Outputing the information
        run: |
          echo "Deploying and uploading......"
