name: callable workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: blabla
        required: true
        type: string
        default: data
    outputs:
      result:
        description: The result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
    # secrets:
    #   some-secret:
    #     required: false
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: download the artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: show the downloaded artifact
        run: ls
      - name: Outputing the information
        run: |
          echo "Deploying and uploading......"
      - name: set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
